name: Setup Rust
description: Setup Rust environment

runs:
    using: composite
    steps:
        - uses: actions/cache@v4
          with:
              path: |
                  ~/.cargo/
                  target/
              key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
