[workspace]
resolver = "2"
members = [
    "mango3-accounts",
    "mango3-cli",
    "mango3-core",
    "mango3-home",
    "mango3-leptos-utils",
    "mango3-my-account",
    "mango3-monitor",
    "mango3-studio",
    "mango3-uploads",
    "mango3-websites",
]

[workspace.package]
edition = "2021"
version = "0.0.0-SNAPSHOT"

[workspace.dependencies]
apalis = "0.6.2"
apalis-redis = "0.6.2"
async-trait = "0.1.83"
axum = "0.7.9"
chrono = {version = "0.4.39", features = ["serde"] }
console_error_panic_hook = "0.1.7"
futures = "0.3.31"
leptos = "0.7.2"
leptos_axum = "0.7.1"
leptos_i18n = { version = "0.5.1", default-features = false, features = [
    "cookie",
    "interpolate_display",
    "yaml_files",
] }
leptos_meta = "0.7.1"
leptos_router = "0.7.1"
leptos-use = { version = "0.14.0", default-features = false }
rust_iso3166 = "0.1.13"
serde = { version = "1.0.216", features = ["derive"] }
server_fn = "0.7.1"
tokio = { version = "1.42.0", features = ["macros", "rt-multi-thread"] }
uuid = { version = "1.11.0", features = ["serde", "v4"] }
wasm-bindgen = "0.2.99"
mango3-core = { path = "mango3-core" }
mango3-leptos-utils = { path = "mango3-leptos-utils" }

[profile.wasm-release]
inherits = "release"
opt-level = 'z'
lto = true
codegen-units = 1
panic = "abort"
