[workspace]
resolver = "2"
members = [
    "mango3-accounts",
    "mango3-cli",
    "mango3-core",
    "mango3-home",
    "mango3-leptos-utils",
    "mango3-my-account",
    "mango3-monitor",
    "mango3-studio",
    "mango3-uploads",
    "mango3-websites",
]

[workspace.package]
edition = "2021"
version = "0.0.0-SNAPSHOT"

[workspace.dependencies]
apalis = { version = "0.5.5", features = ["redis"] }
axum = "0.7.9"
console_error_panic_hook = "0.1.7"
leptos = "0.7.0-rc1"
leptos_axum = "0.7.0-rc1"
leptos_i18n = { version = "0.5.0-rc1", default-features = false, features = ["cookie", "yaml_files"] }
leptos_meta = "0.7.0-rc1"
leptos_router = "0.7.0-rc1"
leptos-use = { version = "0.14.0-rc3", default-features = false }
rust_iso3166 = "0.1.13"
serde = { version = "1.0.215", features = ["derive"] }
server_fn = "0.7.0-rc1"
tokio = { version = "1.41.1", features = ["macros", "rt-multi-thread"] }
uuid = { version = "1.11.0", features = ["serde", "v4"] }
wasm-bindgen = "0.2.95"
mango3-core = { path = "mango3-core" }
mango3-leptos-utils = { path = "mango3-leptos-utils" }

[profile.wasm-release]
inherits = "release"
opt-level = 'z'
lto = true
codegen-units = 1
panic = "abort"
