[workspace]
resolver = "2"
members = [
    "mango3-accounts",
    "mango3-cli",
    "mango3-core",
    "mango3-home",
    "mango3-leptos-utils",
    "mango3-my-account",
    "mango3-monitor",
    "mango3-studio",
    "mango3-uploads",
    "mango3-websites",
]

[workspace.package]
edition = "2021"
version = "0.0.0-SNAPSHOT"

[workspace.dependencies]
apalis = "0.6.4"
apalis-redis = "0.6.4"
async-trait = "0.1.85"
axum = "0.7.9"
chrono = {version = "0.4.39", features = ["serde"] }
console_error_panic_hook = "0.1.7"
futures = "0.3.31"
leptos = "0.7.3"
leptos_axum = "0.7.3"
leptos_i18n = { version = "0.5.5", default-features = false, features = [
    "cookie",
    "interpolate_display",
    "yaml_files",
] }
leptos_meta = "0.7.3"
leptos_router = "0.7.3"
leptos-use = { version = "0.15.4", default-features = false }
regex = "1.11.1"
rust_iso3166 = "0.1.13"
serde_json = { version = "1.0.135" }
serde = { version = "1.0.217", features = ["derive"] }
server_fn = "0.7.3"
tokio = { version = "1.43.0", features = ["macros", "rt-multi-thread"] }
uuid = { version = "1.12.0", features = ["serde", "v4"] }
wasm-bindgen = "0.2.100"
mango3-core = { path = "mango3-core" }
mango3-leptos-utils = { path = "mango3-leptos-utils" }

[profile.wasm-release]
inherits = "release"
opt-level = 'z'
lto = true
codegen-units = 1
panic = "abort"
