[package]
name = "mango3-core"
version.workspace = true
edition.workspace = true

[dependencies]
argon2 = "0.5.3"
apalis = { workspace = true }
apalis-redis = { workspace = true }
dotenvy = "0.15.7"
figment = { version = "0.10.19", features = ["env"] }
fluent-templates = "0.11.0"
fluent-bundle = "0.15.3"
image = "0.25.5"
lazy_static = "1.5.0"
md-5 = "0.10.6"
mime = "0.3.17"
multer = "3.1.0"
rand = "0.8.5"
regex = "1.11.1"
rust_iso3166 = { workspace = true }
serde = { workspace = true }
sqlx = { version = "0.8.2", features = ["chrono", "runtime-tokio", "postgres", "tls-rustls", "uuid"] }
strum = { version = "0.26.3", features = ["derive"] }
unic-langid = { version = "0.9.5", features = ["serde"] }
url = { version = "2.5.4", features = ["serde"] }
uuid = { workspace = true }

[dev-dependencies]
chrono = { workspace = true }
fake = { version = "3.0.1", features = ["chrono", "url"] }
tokio = { workspace = true }
