[package]
name = "mango3-utils"
version.workspace = true
edition.workspace = true

[dependencies]
chrono = { workspace = true }
serde = { workspace = true }
uuid = { workspace = true, optional = true }

[features]
post_reaction = ["uuid"]
