[package]
name = "mango3-cli"
version.workspace = true
edition.workspace = true

[dependencies]
clap = "4.5.31"
tokio = { workspace = true }
mango3-core = { workspace = true, features = ["user_cache_remove"] }
