[package]
name = "mango3-cli"
version.workspace = true
edition.workspace = true

[dependencies]
clap = "4.5.32"
tokio = { workspace = true }
mango3-core = { workspace = true, features = ["invitation_code_insert", "user_cache_remove"] }
mango3-utils = { workspace = true }
