name: Setup database
description: Creates a PostgreSQL database and run migrations

runs:
    using: composite
    steps:
        - name: Configure PostgreSQL
          shell: bash
          run: |
              sudo systemctl restart postgresql.service
              sudo -u postgres psql -c "CREATE USER mango3 ENCRYPTED PASSWORD 'mango3' LOGIN CREATEDB;"
        - name: Install sqlx-cli 
          shell: bash
          run: cargo install --force sqlx-cli --no-default-features --features completions,native-tls,postgres
        - name: Run migrations
          shell: bash
          run: sqlx database setup
