[package]
name = "mango3-leptos-utils"
version.workspace = true
edition.workspace = true

[dependencies]
accept-language = { version = "3.1.0", optional = true }
axum = { version = "0.7.7", optional = true }
axum-extra = { version = "0.9.4", optional = true, features = ["cookie"] }
codee = "0.2"
default-struct-builder = "0.5"
fluent-templates = { workspace = true }
http = { version = "1.1.0", optional = true }
leptos = { workspace = true }
leptos_axum = { version = "0.7.0-rc1", optional = true }
leptos-fluent = { workspace = true }
leptos_meta = { workspace = true }
leptos_router = { workspace = true }
leptos-use = { git = "https://github.com/javierEd/leptos-use.git", default-features = false, features = ["use_color_mode"] }
rust_iso3166 = { workspace = true, optional = true }
serde = { version = "1.0.214", features = ["derive"] }
tokio = { workspace = true, optional = true }
web-sys = "0.3.72"
mango3-core = { workspace = true, optional = true }

[features]
hydrate = ["leptos/hydrate", "leptos-fluent/hydrate"]
ssr = [
    "dep:accept-language",
    "dep:axum",
    "dep:axum-extra",
    "dep:http",
    "dep:leptos_axum",
    "dep:rust_iso3166",
    "dep:tokio",
    "dep:mango3-core",
    "leptos/ssr",
    "leptos-fluent/axum",
    "leptos-fluent/ssr",
    "leptos_meta/ssr",
    "leptos-use/axum",
    "leptos-use/ssr",
]
