name: Build

on:
    workflow_run:
        workflows: [Code analysis]
        types:
            - completed

env:
    DATABASE_URL: postgres://mango3:mango3@localhost:5432/mango3_test

jobs:
    build-monitor:
        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        services:
            postgres:
                image: postgres:17-alpine
                env:
                    POSTGRES_PASSWORD: mango3
                    POSTGRES_USER: mango3
                options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5
                ports:
                    - 5432:5432
        steps:
            - uses: actions/checkout@v4
            - uses: ./.github/actions/setup-rust
            - run: cargo install sqlx-cli
            - run: sqlx database setup
            - name: Build Monitor
              run: cargo build --release --bin mango3-monitor
            - name: Build Uploads
              run: cargo build --release --bin mango3-uploads
            - name: Build CLI
              run: cargo build --release --bin mango3-cli
            - name: Build Home
              run: cargo leptos build --release --project mango3-home
            - name: Build Accounts
              run: cargo leptos build --release --project mango3-accounts
            - name: Build My Account
              run: cargo leptos build --release --project mango3-my-account
            - name: Build Studio
              run: cargo leptos build --release --project mango3-studio
            - name: Build Websites
              run: cargo leptos build --release --project mango3-websites
