name: Builds

on:
    workflow_call:
        inputs:
            skip_accounts:
                default: false
                required: false
                type: boolean
            skip_admin:
                default: false
                required: false
                type: boolean
            skip_cli:
                default: false
                required: false
                type: boolean
            skip_home:
                default: false
                required: false
                type: boolean
            skip_monitor:
                default: false
                required: false
                type: boolean
            skip_my_account:
                default: false
                required: false
                type: boolean
            skip_studio:
                default: false
                required: false
                type: boolean
            skip_uploads:
                default: false
                required: false
                type: boolean
            skip_websites:
                default: false
                required: false
                type: boolean

env:
    CARGO_TERM_COLOR: always
    DATABASE_URL: postgres://mango3:mango3@localhost:5432/mango3_test
    LEPTOS_TAILWIND_VERSION: v4.0.6
    LEPTOS_WASM_OPT_VERSION: version_122

jobs:
    rust_builds:
        runs-on: ubuntu-24.04
        if: ${{ !inputs.skip_cli || !inputs.skip_monitor || !inputs.skip_uploads }}
        steps:
            - uses: actions/checkout@v4
            - uses: ./.github/actions/setup-rust
            - uses: ./.github/actions/setup-database
            - name: Build Monitor
              if: ${{ !inputs.skip_monitor }}
              run: cargo build --release --bin mango3-monitor
            - name: Build Uploads
              if: ${{ !inputs.skip_uploads }}
              run: cargo build --release --bin mango3-uploads
            - name: Build CLI
              if: ${{ !inputs.skip_cli }}
              run: cargo build --release --bin mango3-cli

    leptos_builds:
        runs-on: ubuntu-24.04
        if: ${{
            !inputs.skip_accounts
            || !inputs.skip_admin
            || !inputs.skip_home
            || !inputs.skip_my_account
            || !inputs.skip_studio
            || !inputs.skip_websites
            }}
        steps:
            - uses: actions/checkout@v4
            - uses: ./.github/actions/setup-leptos
            - name: Build Accounts
              if: ${{ !inputs.skip_accounts }}
              run: cargo leptos build --release --project mango3-accounts
            - name: Build Admin
              if: ${{ !inputs.skip_admin }}
              run: cargo leptos build --release --project mango3-admin
            - name: Build Home
              if: ${{ !inputs.skip_home }}
              run: cargo leptos build --release --project mango3-home
            - name: Build My Account
              if: ${{ !inputs.skip_my_account }}
              run: cargo leptos build --release --project mango3-my-account
            - name: Build Studio
              if: ${{ !inputs.skip_studio  }}
              run: cargo leptos build --release --project mango3-studio
            - name: Build Websites
              if: ${{ !inputs.skip_websites  }}
              run: cargo leptos build --release --project mango3-websites
