name: Builds

on: [workflow_call]

env:
    CARGO_TERM_COLOR: always
    DATABASE_URL: postgres://mango3:mango3@localhost:5432/mango3_test
    LEPTOS_WASM_OPT_VERSION: version_119

jobs:
    rust_builds:
        runs-on: ubuntu-24.04
        steps:
            - uses: actions/checkout@v4
            - uses: ./.github/actions/setup-rust
            - uses: ./.github/actions/setup-database
            - name: Build Monitor
              run: cargo build --release --bin mango3-monitor
            - name: Build Uploads
              run: cargo build --release --bin mango3-uploads
            - name: Build CLI
              run: cargo build --release --bin mango3-cli

    leptos_builds:
        runs-on: ubuntu-24.04
        steps:
            - uses: actions/checkout@v4
            - uses: ./.github/actions/setup-leptos
            - name: Build Home
              run: cargo leptos build --release --project mango3-home
            - name: Build Accounts
              run: cargo leptos build --release --project mango3-accounts
            - name: Build My Account
              run: cargo leptos build --release --project mango3-my-account
            - name: Build Studio
              run: cargo leptos build --release --project mango3-studio
            - name: Build Websites
              run: cargo leptos build --release --project mango3-websites
