name: CI

on:
    push:
        branches: [main]
        paths-ignore:
            - "assets/*"
            - "config/*"
            - "*.md"
            - LICENSE
    pull_request:
        branches: [main]
        paths-ignore:
            - "assets/*"
            - "config/*"
            - "*.md"
            - LICENSE

jobs:
    changes:
        runs-on: ubuntu-24.04
        name: Check changes
        outputs:
            rust: ${{ steps.filter.outputs.rust }}
            sql: ${{ steps.filter.outputs.sql }}
            accounts: ${{ steps.filter.outputs.accounts }}
            cli: ${{ steps.filter.outputs.cli }}
            home: ${{ steps.filter.outputs.home }}
            monitor: ${{ steps.filter.outputs.monitor }}
            my_account: ${{ steps.filter.outputs.my_account }}
            studio: ${{ steps.filter.outputs.studio }}
            uploads: ${{ steps.filter.outputs.uploads }}
            websites: ${{ steps.filter.outputs.websites }}
        steps:
            - uses: actions/checkout@v4
              name: Determine changed files
            - uses: dorny/paths-filter@v3
              id: filter
              with:
                  base: main
                  filters: |
                      css_js:
                          - 'js/*'
                          - 'style/*'
                          - 'package.json'
                          - 'package-lock.json'
                          - 'tailwind.config.js'
                      rust:
                          - '.clippy.toml'
                          - '.rustfmt.toml'
                          - 'leptosfmt.toml'
                          - 'rust-toolchain.toml'
                          - 'locales/**'
                          - '**.rs'
                          - 'Cargo.lock'
                          - 'Cargo.toml'
                          - '*/Cargo.toml'
                      sql:
                          - '.sqlfluff'
                          - 'migrations/*.sql'
                      workspace:
                          - 'Cargo.lock'
                          - 'Cargo.toml'
                          - 'mango3-core/**'
                          - 'migrations/*.sql'
                      accounts:
                          - 'mango3-leptos-utils/**'
                          - 'mango3-accounts/src/**.rs'
                          - 'mango3-accounts/Cargo.toml'
                      accounts_e2e:
                          - 'mango3-accounts/end2end/**'
                      cli:
                          - 'mango3-cli/**'
                      home:
                          - 'mango3-leptos-utils/**'
                          - 'mango3-home/src/**'
                          - 'mango3-home/Cargo.toml'
                      home_e2e:
                          - 'mango3-home/end2end/**'
                      monitor:
                          - 'mango3-monitor/**'
                      my_account:
                          - 'mango3-leptos-utils/**'
                          - 'mango3-my-account/src/**'
                          - 'mango3-my-account/Cargo.toml'
                      my_account_e2e:
                          - 'mango3-my-account/end2end/**'
                      studio:
                          - 'mango3-leptos-utils/**'
                          - 'mango3-studio/src/**'
                          - 'mango3-studio/Cargo.toml'
                      studio_e2e:
                          - 'mango3-studio/end2end/**'
                      uploads:
                          - 'mango3-uploads/**'
                      websites:
                          - 'mango3-leptos-utils/**'
                          - 'mango3-websites/src/**'
                          - 'mango3-websites/Cargo.toml'
                      websites_e2e:
                          - 'mango3-websites/end2end/**'

    code_analysis:
        needs: changes
        uses: ./.github/workflows/code_analysis.yaml
        with:
            skip_rust: ${{ needs.changes.outputs.rust == 'false' }}
            skip_sql: ${{ needs.changes.outputs.sql == 'false' }}

    builds:
        needs: [changes, code_analysis]
        if: ${{ success() || needs.code_analysis.result == 'skipped' }}
        uses: ./.github/workflows/builds.yaml
        with:
            skip_accounts: ${{ needs.changes.outputs.workspace == 'false' && needs.changes.outputs.accounts == 'false' }}
            skip_cli: ${{ needs.changes.outputs.workspace == 'false' && needs.changes.outputs.cli == 'false' }}
            skip_home: ${{ needs.changes.outputs.workspace == 'false' && needs.changes.outputs.home == 'false' }}
            skip_monitor: ${{ needs.changes.outputs.workspace == 'false' && needs.changes.outputs.monitor == 'false' }}
            skip_my_account: ${{ needs.changes.outputs.workspace == 'false' && needs.changes.outputs.my_account == 'false' }}
            skip_studio: ${{ needs.changes.outputs.workspace == 'false' && needs.changes.outputs.studio == 'false' }}
            skip_uploads: ${{ needs.changes.outputs.workspace == 'false' && needs.changes.outputs.uploads == 'false' }}
            skip_websites: ${{ needs.changes.outputs.workspace == 'false' && needs.changes.outputs.websites == 'false' }}

    tests:
        needs: [changes, builds]
        if: ${{ success() || needs.builds.result == 'skipped' }}
        uses: ./.github/workflows/tests.yaml
        with:
            skip_unit: ${{ needs.changes.outputs.rust == 'false' }}
            skip_accounts_e2e: ${{ needs.changes.outputs.css_js == 'false' && needs.changes.outputs.workspace == 'false' && needs.changes.outputs.accounts == 'false' && needs.changes.outputs.accounts_e2e == 'false' }}
            skip_home_e2e: ${{ needs.changes.outputs.css_js == 'false' && needs.changes.outputs.workspace == 'false' && needs.changes.outputs.css_js == 'false' && needs.changes.outputs.workspace == 'false' && needs.changes.outputs.home == 'false' && needs.changes.outputs.home_e2e == 'false' }}
            skip_my_account_e2e: ${{ needs.changes.outputs.css_js == 'false' && needs.changes.outputs.workspace == 'false' && needs.changes.outputs.my_account == 'false' && needs.changes.outputs.my_account_e2e == 'false' }}
            skip_studio_e2e: ${{ needs.changes.outputs.css_js == 'false' && needs.changes.outputs.workspace == 'false' && needs.changes.outputs.studio == 'false' && needs.changes.outputs.studio_e2e == 'false' }}
            skip_websites_e2e: ${{ needs.changes.outputs.css_js == 'false' && needs.changes.outputs.workspace == 'false' && needs.changes.outputs.websites == 'false' && needs.changes.outputs.websites_e2e == 'false' }}
