name: CI

on:
    push:
        branches: [main]
        paths-ignore:
            - "assets/*"
            - "config/*"
            - "*.md"
            - LICENSE
    pull_request:
        branches: [main]
        paths-ignore:
            - "assets/*"
            - "config/*"
            - "*.md"
            - LICENSE

jobs:
    changes:
        runs-on: ubuntu-24.04
        name: Check changes
        steps:
            - uses: actions/checkout@v4
              name: Determine changed files
            - uses: dorny/paths-filter@v3
              id: filter
              with:
                  base: main
                  filters: |
                      css_js: &css_js
                          - 'js/**'
                          - 'style/**'
                          - 'package.json'
                          - 'package-lock.json'
                          - 'tailwind.config.js'
                      rust:
                          - '.clippy.toml'
                          - '.github/workflows/code_analysis.yaml'
                          - '.github/workflows/tests.yaml'
                          - '.rustfmt.toml'
                          - 'leptosfmt.toml'
                          - 'rust-toolchain.toml'
                          - 'locales/leptos/**'
                          - '**.rs'
                          - 'Cargo.lock'
                          - 'Cargo.toml'
                          - '*/Cargo.toml'
                      sql:
                          - '.github/workflows/code_analysis.yaml'
                          - '.sqlfluff'
                          - 'migrations/*.sql'
                      workspace: &workspace
                          - '.github/workflows/builds.yaml'
                          - '.github/workflows/tests.yaml'
                          - 'Cargo.lock'
                          - 'Cargo.toml'
                          - 'packs/mango3-core/**'
                          - 'migrations/*.sql'
                      accounts: &accounts
                          - *workspace
                          - 'webpacks/mango3-web-utils/**'
                          - 'webpacks/mango3-accounts/src/**'
                          - 'webpacks/mango3-accounts/Cargo.toml'
                      accounts_e2e:
                          - *accounts
                          - *css_js
                          - 'webpacks/mango3-accounts/end2end/**'
                      admin: &admin
                          - *workspace
                          - 'webpacks/mango3-web-utils/**'
                          - 'webpacks/mango3-admin/src/**'
                          - 'webpacks/mango3-admin/Cargo.toml'
                      admin_e2e:
                          - *admin
                          - *css_js
                          - 'webpacks/mango3-admin/end2end/**'
                      cli:
                          - *workspace
                          - 'mango3-cli/**'
                      home: &home
                          - *workspace
                          - 'webpacks/mango3-web-utils/**'
                          - 'webpacks/mango3-home/src/**'
                          - 'webpacks/mango3-home/Cargo.toml'
                      home_e2e:
                          - *home
                          - *css_js
                          - 'webpacks/mango3-home/end2end/**'
                      monitor:
                          - *workspace
                          - 'mango3-monitor/**'
                      my_account: &my_account
                          - *workspace
                          - 'webpacks/mango3-web-utils/**'
                          - 'webpacks/mango3-my-account/src/**'
                          - 'webpacks/mango3-my-account/Cargo.toml'
                      my_account_e2e:
                          - *my_account
                          - *css_js
                          - 'webpacks/mango3-my-account/end2end/**'
                      studio: &studio
                          - *workspace
                          - 'webpacks/mango3-web-utils/**'
                          - 'webpacks/mango3-studio/src/**'
                          - 'webpacks/mango3-studio/Cargo.toml'
                      studio_e2e:
                          - *studio
                          - *css_js
                          - 'webpacks/mango3-studio/end2end/**'
                      uploads:
                          - *workspace
                          - 'mango3-uploads/**'
                      websites: &websites
                          - *workspace
                          - 'webpacks/mango3-web-utils/**'
                          - 'webpacks/mango3-websites/src/**'
                          - 'webpacks/mango3-websites/Cargo.toml'
                      websites_e2e:
                          - *websites
                          - *css_js
                          - 'webpacks/mango3-websites/end2end/**'
        outputs:
            rust: ${{ steps.filter.outputs.rust }}
            sql: ${{ steps.filter.outputs.sql }}
            accounts: ${{ steps.filter.outputs.accounts }}
            accounts_e2e: ${{ steps.filter.outputs.accounts_e2e }}
            admin: ${{ steps.filter.outputs.admin }}
            admin_e2e: ${{ steps.filter.outputs.admin_e2e }}
            cli: ${{ steps.filter.outputs.cli }}
            home: ${{ steps.filter.outputs.home }}
            home_e2e: ${{ steps.filter.outputs.home_e2e }}
            monitor: ${{ steps.filter.outputs.monitor }}
            my_account: ${{ steps.filter.outputs.my_account }}
            my_account_e2e: ${{ steps.filter.outputs.my_account_e2e }}
            studio: ${{ steps.filter.outputs.studio }}
            studio_e2e: ${{ steps.filter.outputs.studio_e2e }}
            uploads: ${{ steps.filter.outputs.uploads }}
            websites: ${{ steps.filter.outputs.websites }}
            websites_e2e: ${{ steps.filter.outputs.websites_e2e }}

    code_analysis:
        needs: changes
        uses: ./.github/workflows/code_analysis.yaml
        with:
            skip_rust: ${{ needs.changes.outputs.rust == 'false' }}
            skip_sql: ${{ needs.changes.outputs.sql == 'false' }}

    builds:
        needs: [changes, code_analysis]
        if: ${{ always() && !contains(needs.*.result, 'failure') && !contains(needs.*.result, 'cancelled') }}
        uses: ./.github/workflows/builds.yaml
        with:
            skip_accounts: ${{ needs.changes.outputs.accounts == 'false' }}
            skip_admin: ${{ needs.changes.outputs.admin == 'false' }}
            skip_cli: ${{ needs.changes.outputs.cli == 'false' }}
            skip_home: ${{ needs.changes.outputs.home == 'false' }}
            skip_monitor: ${{ needs.changes.outputs.monitor == 'false' }}
            skip_my_account: ${{ needs.changes.outputs.my_account == 'false' }}
            skip_studio: ${{ needs.changes.outputs.studio == 'false' }}
            skip_uploads: ${{ needs.changes.outputs.uploads == 'false' }}
            skip_websites: ${{ needs.changes.outputs.websites == 'false' }}

    tests:
        needs: [changes, builds]
        if: ${{ always() && !contains(needs.*.result, 'failure') && !contains(needs.*.result, 'cancelled') }}
        uses: ./.github/workflows/tests.yaml
        with:
            skip_unit: ${{ needs.changes.outputs.rust == 'false' }}
            skip_accounts_e2e: ${{ needs.changes.outputs.accounts_e2e == 'false' }}
            skip_admin_e2e: ${{ needs.changes.outputs.admin_e2e == 'false' }}
            skip_home_e2e: ${{ needs.changes.outputs.home_e2e == 'false' }}
            skip_my_account_e2e: ${{ needs.changes.outputs.my_account_e2e == 'false' }}
            skip_studio_e2e: ${{ needs.changes.outputs.studio_e2e == 'false' }}
            skip_websites_e2e: ${{ needs.changes.outputs.websites_e2e == 'false' }}
