name: Code analysis

on: [push, pull_request]

env:
    DATABASE_URL: postgres://mango3:mango3@postgres:5432/mango3_test
    # JOBS_REDIS_URL: redis://redis:6379/0
    # SESSIONS_REDIS_URL: redis://redis:6379/1

jobs:
    cargo-clippy:
        runs-on: ubuntu-latest
        services:
            postgres:
                image: postgres:17-alpine
                env:
                    POSTGRES_PASSWORD: mango3
                    POSTGRES_USER: mango3
            # redis:
            #     image: redis:7-alpine
        steps:
            - uses: ./.github/actions/setup-rust
            - run: cargo install sqlx
            - run: sqlx database setup
            - run: cargo clippy -- -D warnings

    cargo-fmt:
        runs-on: ubuntu-latest
        steps:
            - uses: ./.github/actions/setup-rust
            - run: cargo fmt --all --check

    leptosfmt:
        runs-on: ubuntu-latest
        steps:
            - uses: ./.github/actions/setup-rust
            - run: cargo install leptosfmt
            - run: leptosfmt --check -x mango3-cli -x mango3-core -x mango3-monitor -x mango3-uploads -x target .

    sqlfluff:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v4
            - run: pip install --upgrade pipenv~=2024.4
            - uses: actions/cache@v4
              with:
                  path: ~/.local/share/virtualenvs
                  key: ${{ runner.os }}-python-${{ steps.setup-python.outputs.python-version }}-pipenv-${{ hashFiles('Pipfile.lock') }}
            - run: pipenv install sqlfluff~=3.2
            - run: pipenv run sqlfluff lint migrations/*.sql
