name: Tests

on: [workflow_call]

env:
    DATABASE_URL: postgres://mango3:mango3@localhost:5432/mango3_test

jobs:
    test-monitor:
        runs-on: ubuntu-latest
        services:
            postgres:
                image: postgres:17-alpine
                env:
                    POSTGRES_PASSWORD: mango3
                    POSTGRES_USER: mango3
                options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
                ports:
                    - 5432:5432
        steps:
            - uses: actions/checkout@v4
            - uses: ./.github/actions/setup-rust
            - uses: ./.github/actions/setup-database
            - name: Test Monitor
              run: cargo test --bin mango3-monitor

    test-uploads:
        runs-on: ubuntu-latest
        services:
            postgres:
                image: postgres:17-alpine
                env:
                    POSTGRES_PASSWORD: mango3
                    POSTGRES_USER: mango3
                options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
                ports:
                    - 5432:5432
        steps:
            - uses: actions/checkout@v4
            - uses: ./.github/actions/setup-rust
            - uses: ./.github/actions/setup-database
            - name: Test Uploads
              run: cargo build --bin mango3-uploads

    test-cli:
        runs-on: ubuntu-latest
        services:
            postgres:
                image: postgres:17-alpine
                env:
                    POSTGRES_PASSWORD: mango3
                    POSTGRES_USER: mango3
                options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
                ports:
                    - 5432:5432
        steps:
            - uses: actions/checkout@v4
            - uses: ./.github/actions/setup-rust
            - uses: ./.github/actions/setup-database
            - name: Test CLI
              run: cargo test --bin mango3-cli
