name: Tests

on: [workflow_call]

env:
    CARGO_TERM_COLOR: always
    DATABASE_URL: postgres://mango3:mango3@localhost:5432/mango3_test
    JOBS_REDIS_URL: redis://127.0.0.1:6379/10
    LEPTOS_WASM_OPT_VERSION: version_119
    SESSIONS_REDIS_URL: redis://127.0.0.1:6379/11

jobs:
    unit_tests:
        runs-on: ubuntu-24.04
        services:
            redis:
                image: redis:7-alpine
                options: --health-cmd "redis-cli ping" --health-interval 10s --health-timeout 5s --health-retries 5
                ports:
                    - 6379:6379

        steps:
            - uses: actions/checkout@v4
            - uses: taiki-e/install-action@nextest
            - uses: ./.github/actions/setup-rust
            - uses: ./.github/actions/setup-database
            - name: Run all unit tests
              run: cargo nextest run --workspace --all-features

    end2end_tests:
        runs-on: ubuntu-24.04
        services:
            redis:
                image: redis:7-alpine
                options: --health-cmd "redis-cli ping" --health-interval 10s --health-timeout 5s --health-retries 5
                ports:
                    - 6379:6379

        steps:
            - uses: actions/checkout@v4
            - uses: ./.github/actions/setup-leptos
            - name: Configure Nginx
              run: |
                  sudo cp ${{ github.workspace }}/config/nginx.example /etc/nginx/sites-enabled/mango3.local
                  sudo sed -i 's/user www-data/user root/' /etc/nginx/nginx.conf
                  sudo sed -i 's|root /mango3|root ${{ github.workspace }}|g' /etc/nginx/sites-enabled/mango3.local
                  sudo sed -i \
                      's/127.0.0.1 localhost/127.0.0.1 localhost mango3.local accounts.mango3.local my-account.mango3.local studio.mango3.local my-website.mango3.local/' \
                      /etc/hosts
                  sudo systemctl restart nginx.service
            - name: Install Playwright
              run: npx playwright install chromium firefox --with-deps
            - name: Test Accounts
              run: cargo leptos end-to-end --project mango3-accounts
            - name: Test Home
              run: cargo leptos end-to-end --project mango3-home
            - name: Test My Account
              run: cargo leptos end-to-end --project mango3-my-account
            - name: Test Studio
              run: cargo leptos end-to-end --project mango3-studio
            - name: Test Websites
              run: cargo leptos end-to-end --project mango3-websites
