name: Tests

on: [workflow_call]

env:
    DATABASE_URL: postgres://mango3:mango3@localhost:5432/mango3_test

jobs:
    unit_tests:
        runs-on: ubuntu-latest
        services:
            postgres:
                image: postgres:17-alpine
                env:
                    POSTGRES_PASSWORD: mango3
                    POSTGRES_USER: mango3
                options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
                ports:
                    - 5432:5432

        steps:
            - uses: actions/checkout@v4
            - uses: ./.github/actions/setup-rust
            - uses: ./.github/actions/setup-database
            - name: Run all unit tests
              run: cargo test --workspace --all-features

    end2end_tests:
        runs-on: ubuntu-latest
        services:
            nginx:
                image: nginx:1-alpine
                ports:
                    - 80:80
                volumes:
                    - ${{ github.workspace }}/config/nginx.example:/etc/sites-enabled/mango3.conf
                    - ${{ github.workspace }}/assets:/mango3/assets

            postgres:
                image: postgres:17-alpine
                env:
                    POSTGRES_PASSWORD: mango3
                    POSTGRES_USER: mango3
                options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
                ports:
                    - 5432:5432

            redis:
                image: redis:7-alpine
                options: --health-cmd "redis-cli ping" --health-interval 10s --health-timeout 5s --health-retries 5
                ports:
                    - 6379:6379

        steps:
            - uses: actions/checkout@v4
            - uses: ./.github/actions/setup-leptos
            - run: npx playwright install chromium firefox --with-deps
            - run: |
                  sudo sed -i \
                  's/localhost/localhost mango3.local accounts.mango3.local my-account.mango3.local studio.mango3.local my.website.mango3.local/g' \
                  /etc/hosts
            - name: Test Home
              run: cargo leptos end-to-end --project mango3-home
            - name: Test Accounts
              run: cargo leptos end-to-end --project mango3-accounts
            - name: Test My Account
              run: cargo leptos end-to-end --project mango3-my-account
            - name: Test Studio
              run: cargo leptos end-to-end --project mango3-studio
            - name: Test Websites
              run: cargo leptos end-to-end --project mango3-websites
